### ISSUE TITLE
DB 변경된 사항에 대한 view.py 코드 부분 수정

### ISSUE THREAD

**Issue by huh-min** [huh-min/capstone2-2020#11]
추가된 categorydata table과 수정된 clothes 테이블과 관련된 부분들의 수정 작업

- [ ] clothes table

- [ ] categorydata

**Comment by huh-min** [comment]
변경된 DB을 기준으로, 사용자에게 내 옷장에서 출력되는 대분류/소분류 데이터 추적 경로를 기존의 clothes.upper_category에서 clothes.category.upper_category로 수정하여 정상출력이 됨.

**Comment by huh-min** [comment]
새로운 옷을 등록하고 그에 따른 대분류/소분류 데이터를 DB에 입력하는 경로가 잘 작동하는지 확인해야 하는데, 현재 옷을 새로 등록할 수 없어서 다른 방법을 검토 중.

**Comment by huh-min** [comment]
따라서 기존의 clothes table 컬럼인 upper와lower는 아직 남겨둔 상태

**Comment by kmu-yoonsh** [comment]
새로운 옷을 등록할 수 없는 이유가? front-end 문제인가요? 
만약 그렇다면 back-end에 명령어 형식을 맞춰서 호출해서 테스트 하는 방법도 고민해보세요. 
보통은 unittest로 구현하지만 그렇게 무겁게 생각할 필요는 없고...
