### ISSUE TITLE
view.py 내 공통 함수 정리

### ISSUE THREAD

**Issue by huh-min** [huh-min/capstone2-2020#12]
반복 코드나 비슷한 코드 정리하여 효율성 UP

class 확인 후 공통함수로 취급할 것들을 선정하여

class별로 정리 (ex. 코디 update & create)

**Comment by kmu-yoonsh** [comment]
공통 함수들이 클래스를 넘나들며 많다면 -  상속 관계나 별도의 클래스 작성을 고려해야 할 수 있습니다.

**Comment by huh-min** [comment]
perform_create
: create(0의 동작 중 일부분을 오버라이딩한다고 생각하면 되는데,
serializer.save()가 호출될 때 perform_create가 호출된다고 생각하면 됨.

**Comment by huh-min** [comment]
각 클래스는 viewset이라는 추상 클래스를 상속중.
ModelViewSet 클래스는 mixin 클래스를 사용하며
create(), list(), update(), destroy()같은 기능을 모두 제공
그래서 선언하지 않아도 기본적으로 선언된 메서드들을 사용할 수 있는데,
현재 우리 코드의 클래스에서는 각각 오버라이딩을 한 상태
