### ISSUE TITLE
view.py 에서 target_clothes[0].owner.id 타입 확인 및 연산 방식 수정

### ISSUE THREAD

**Issue by huh-min** [huh-min/capstone2-2020#13]
- view.py 의 line 173 에 target_clothes[0].owner.id 의 타입을 확인한 후 id가 int아니면 db구조 자체 수정

**Comment by kmu-yoonsh** [comment]
무슨 의미일까요?  
owner.id도 결국 우리가 만든 데이터일 텐데...

**Comment by huh-min** [comment]
owner.id로 가져오면 string 값으로 가져오는데, int 연산을 해야해서 int()로 묶어줌
