### ISSUE TITLE
데모 

### ISSUE THREAD

**Issue by kmu-yoonsh** [huh-min/capstone2-2020#22]
현재 이슈를 살펴보면 실행이 안되는 것 같습니다. 
최종 미팅때는 시연이 필요하므로 수정한 부분들에 대한 기능 테스트 꼭 해주세요. 

최종 미팅은 1월 4일 5시로 하죠~ 혹시 면접 등의 사유로 변경이 필요하면 알려주세요.

**Comment by gyqls980** [comment]
넵 알겠습니다. 그런데 혹시 최종 미팅 날짜는 12월 4일 말씀하신걸까요?
